version: "3.7"
services:
  mtombs:
    image: motbms-services:1.0.0
    ports:
      - 8080:9090
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/motbms3?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "psapmysqlimage:1.0.0"
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: motbms3
      MYSQL_ROOT_PASSWORD: Job@2024
networks:
  springapimysql-net: