version: "3.7"
services:
  mtombs:
    image: motbms-app:1.0.0
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/sapdb1?allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=Job@2024

      - spring.data.elasticsearch.cluster-names=elasticsearch
      - spring.data.elasticsearch.cluster-node=elasticsearch:9200
      - index.theatre.geo.distance=50km
    depends_on:
      - mysqldb
      - elasticsearch

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: mysql:5.7
    volumes:
      - ./database/db-script1.sql:/docker-entrypoint-initdb.d/db-script1.sql
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: sapdb1
      MYSQL_ROOT_PASSWORD: Job@2024


  # Service ElasticSearch
  elasticsearch:
    image: elastic/elasticsearch:8.8.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

    environment:
      - http.host=0.0.0.0
      - transport.host=elasticsearch
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=elasticsearch
      - discovery.type=single-node

    ulimits:
      memlock:
        soft: -1
        hard: -1

    networks:
      - springapimysql-net


networks:
  springapimysql-net:
    driver: bridge