apiVersion: v1
kind: Service
metadata:
  name: sapmysql
  labels:
    app: sapmysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: sapmysql
    tier: database
    clusterIP: None