version: "3.7"
services:
  mtombs:
    image: motbms-services:1.0.0
    ports:
      - 8080:9090
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/sapdb1?allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=Job@2024

      - spring.data.elasticsearch.cluster-names=elasticsearch
      - spring.data.elasticsearch.cluster-node=elasticsearch:9200
      - index.theatre.geo.distance=50km
    depends_on:
      - mysqldb
      - elasticsearch

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: mysql:5.7
    volumes:
      - ./db-script1.sql:/docker-entrypoint-initdb.d/db-script1.sql
    ports:
      - 3306:8084
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: sapdb1
      MYSQL_ROOT_PASSWORD: Job@2024


  # Service ElasticSearch
  elasticsearch:
    image: elastic/elasticsearch:6.2.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - springapimysql-net


networks:
  springapimysql-net:
    driver: bridge



